# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# ✅ CREDENCIALES DE Essential_v1 (de tus imágenes)
client_id = "b79e2fb8bcb7a5671f55e60712f610c2"
name = "Essential_v1"
handle = "essential-v1"
application_url = "https://essential-production.up.railway.app/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders"

[auth]
redirect_urls = [ 
  "https://essential-production.up.railway.app/api/auth",
  "https://essential-production.up.railway.app/auth/callback"
]

[pos]
embedded = false