# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b79e2fb8bcb7a5671f55e60712f610c2"
name = "Essential_v1"
handle = "essential-v1"
application_url = "https://personals-assuming-idle-billy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://landscapes-strengths-spin-outcome.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://landscapes-strengths-spin-outcome.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = ["https://personals-assuming-idle-billy.trycloudflare.com/auth/callback", "https://personals-assuming-idle-billy.trycloudflare.com/auth/shopify/callback", "https://personals-assuming-idle-billy.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
